//! M4 proof — snapshot the three native instruction outputs from one canonical
//! doc, verify AGENTS.md is verbatim, and verify a skill folder copies
//! byte-identically (placement, not translation).

use std::fs;

use canonical::{Instructions, Skill};
use projection::{
    place_skill, plan_skill_placement, project_agents_md, project_instructions, SkillPlacement,
    Target,
};

fn doc() -> Instructions {
    Instructions {
        markdown: "# Project rules\n\n- Prefer small diffs.\n- Tests before claims.".into(),
    }
}

#[test]
fn instructions_snapshot_claude() {
    let a = project_instructions(Target::Claude, &doc());
    let expected = "<!-- Generated by Agent Bridge from the canonical instructions doc. \
             Edit the canonical entity, not this file. Equivalent, not identical. -->\n\n\
# Project rules\n\n- Prefer small diffs.\n- Tests before claims.\n";
    assert_eq!(a.contents, expected);
    assert_eq!(a.path, "CLAUDE.md");
}

#[test]
fn instructions_snapshot_cursor_uses_hash_banner() {
    let a = project_instructions(Target::Cursor, &doc());
    let expected = "# Generated by Agent Bridge from the canonical instructions doc.\n\
             # Edit the canonical entity, not this file. Equivalent, not identical.\n\n\
# Project rules\n\n- Prefer small diffs.\n- Tests before claims.\n";
    assert_eq!(a.contents, expected);
    assert_eq!(a.path, ".cursorrules");
}

#[test]
fn same_canonical_body_appears_in_all_three() {
    let bodies: Vec<String> = [Target::Claude, Target::Codex, Target::Cursor]
        .into_iter()
        .map(|t| project_instructions(t, &doc()).contents)
        .collect();
    for b in &bodies {
        assert!(b.contains("Prefer small diffs."));
        assert!(b.contains("Tests before claims."));
    }
    // Different native paths, same instruction substance.
    assert_ne!(bodies[0], bodies[2]); // banners differ (html vs hash)
}

#[test]
fn agents_md_passes_through_unchanged() {
    let body = "# Repo knowledge\n\nThis is a Tauri + Rust workspace.\n";
    assert_eq!(project_agents_md(body).contents, body);
}

#[test]
fn skill_folder_copies_byte_for_byte() {
    let tmp = tempfile::tempdir().unwrap();
    // A fake skill folder with SKILL.md + a script.
    let src = tmp.path().join("src/profile");
    fs::create_dir_all(&src).unwrap();
    fs::write(src.join("SKILL.md"), "---\nname: profile\n---\nAnalyze history.").unwrap();
    fs::create_dir_all(src.join("scripts")).unwrap();
    fs::write(src.join("scripts/run.sh"), "#!/bin/sh\necho hi\n").unwrap();

    let skills_root = tmp.path().join(".claude/skills");
    let skills = vec![Skill { name: "profile".into(), source_dir: src.to_string_lossy().into() }];
    let plan = plan_skill_placement(Target::Claude, &skills, &skills_root);
    place_skill(&plan[0]).unwrap();

    let dst = skills_root.join("profile");
    assert_eq!(
        fs::read_to_string(dst.join("SKILL.md")).unwrap(),
        fs::read_to_string(src.join("SKILL.md")).unwrap(),
        "SKILL.md must copy verbatim — no translation"
    );
    assert_eq!(
        fs::read_to_string(dst.join("scripts/run.sh")).unwrap(),
        "#!/bin/sh\necho hi\n"
    );
}

#[test]
fn placing_a_skill_twice_is_idempotent() {
    let tmp = tempfile::tempdir().unwrap();
    let src = tmp.path().join("src/profile");
    fs::create_dir_all(&src).unwrap();
    fs::write(src.join("SKILL.md"), "v1").unwrap();

    let p = SkillPlacement {
        target: Target::Claude,
        skill: "profile".into(),
        source_dir: src.to_string_lossy().into(),
        target_dir: tmp.path().join("dst/profile").to_string_lossy().into(),
    };
    place_skill(&p).unwrap();
    // Change the source, re-place — destination must reflect the new source, with
    // no stale files left behind.
    fs::write(src.join("SKILL.md"), "v2").unwrap();
    place_skill(&p).unwrap();
    assert_eq!(fs::read_to_string(tmp.path().join("dst/profile/SKILL.md")).unwrap(), "v2");
}
