//! Instructions projection — one canonical instructions doc → each agent's
//! native instruction surface (plan §3a, PRD FR9).
//!
//! Unlike MCP/skills, instructions *project* cleanly but do **not** *behave*
//! identically: each agent injects and weights them differently. So every
//! artifact carries `equivalent_not_identical: true` and a human note — the
//! honesty flag is part of the data, not something the UI must remember to add
//! (NFR2).

use canonical::Instructions;
use serde::{Deserialize, Serialize};

use crate::Target;

/// A projected instruction file for one target.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InstructionArtifact {
    /// Target agent.
    pub target: Target,
    /// Relative native path to write (e.g. `CLAUDE.md`).
    pub path: String,
    /// File body (canonical markdown + a generated banner).
    pub contents: String,
    /// Always true: projected instructions are equivalent, not identical.
    pub equivalent_not_identical: bool,
    /// Human-readable caveat the UI surfaces next to this projection.
    pub fidelity_note: String,
}

const NOTE: &str = "Projected from the canonical instructions doc. Behavior is \
equivalent, not identical — each agent injects and weights instructions differently.";

/// The native instruction file path for a target.
pub fn instructions_path(target: Target) -> &'static str {
    match target {
        Target::Claude => "CLAUDE.md",
        // Codex's native instruction surface is AGENTS.md (it co-locates
        // instructions with repo knowledge — itself an "equivalent not identical"
        // reality vs Claude's dedicated CLAUDE.md).
        Target::Codex => "AGENTS.md",
        Target::Cursor => ".cursorrules",
    }
}

/// Project the canonical instructions doc into `target`'s native file.
pub fn project_instructions(target: Target, ins: &Instructions) -> InstructionArtifact {
    let banner: &str = match target {
        // Markdown surfaces take an HTML-comment banner.
        Target::Claude | Target::Codex => {
            "<!-- Generated by Agent Bridge from the canonical instructions doc. \
             Edit the canonical entity, not this file. Equivalent, not identical. -->\n\n"
        }
        // .cursorrules is plain text → hash-comment banner.
        Target::Cursor => {
            "# Generated by Agent Bridge from the canonical instructions doc.\n\
             # Edit the canonical entity, not this file. Equivalent, not identical.\n\n"
        }
    };

    let body = ins.markdown.trim_end_matches('\n');
    InstructionArtifact {
        target,
        path: instructions_path(target).to_string(),
        contents: format!("{banner}{body}\n"),
        equivalent_not_identical: true,
        fidelity_note: NOTE.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn doc() -> Instructions {
        Instructions { markdown: "# Rules\n\n- Be concise.\n- Verify before claiming done.".into() }
    }

    #[test]
    fn projects_to_the_right_native_path_per_target() {
        assert_eq!(project_instructions(Target::Claude, &doc()).path, "CLAUDE.md");
        assert_eq!(project_instructions(Target::Codex, &doc()).path, "AGENTS.md");
        assert_eq!(project_instructions(Target::Cursor, &doc()).path, ".cursorrules");
    }

    #[test]
    fn every_artifact_is_flagged_equivalent_not_identical() {
        for target in [Target::Claude, Target::Codex, Target::Cursor] {
            let a = project_instructions(target, &doc());
            assert!(a.equivalent_not_identical);
            assert!(!a.fidelity_note.is_empty());
            // The canonical body survives intact.
            assert!(a.contents.contains("Be concise."));
            assert!(a.contents.contains("Verify before claiming done."));
        }
    }

    #[test]
    fn markdown_targets_use_html_banner_cursor_uses_hash() {
        assert!(project_instructions(Target::Claude, &doc()).contents.starts_with("<!--"));
        assert!(project_instructions(Target::Cursor, &doc()).contents.starts_with("# Generated"));
    }
}
